#ifndef NAIVEBAYESCLASSIFIER_GLOBAL_H
#define NAIVEBAYESCLASSIFIER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NAIVEBAYESCLASSIFIER_LIBRARY)
#  define NAIVEBAYESCLASSIFIERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define NAIVEBAYESCLASSIFIERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // NAIVEBAYESCLASSIFIER_GLOBAL_H
