#ifndef CORPUSHANDLER_GLOBAL_H
#define CORPUSHANDLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CORPUSHANDLER_LIBRARY)
#  define CORPUSHANDLERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CORPUSHANDLERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CORPUSHANDLER_GLOBAL_H
