#ifndef CONFIGSERVICE_GLOBAL_H
#define CONFIGSERVICE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CONFIGSERVICE_LIBRARY)
#  define CONFIGSERVICESHARED_EXPORT Q_DECL_EXPORT
#else
#  define CONFIGSERVICESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CONFIGSERVICE_GLOBAL_H
